apiVersion: apps/v1
kind: Deployment
metadata:
  name: wildfly-gym-pod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wildfly-gym-pod
  template:
    metadata:
      labels:
        app: wildfly-gym-pod
    spec:
      containers:
      - name: wildfly-gym-container
        image: wildfly-gym:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 8080
      restartPolicy: Always