version: "3"
services:
  app:
    image: wildfly-gym
    ports:
      - 8080:8080
    volumes:
      - .:/app
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gym
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgres/data
