apiVersion: v1
kind: Service
metadata:
  name: wildfly-gym-lb-svc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: wildfly-gym-pod
  type: LoadBalancer