apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wildfly-gym-db-st
spec:
  serviceName: wildfly-gym-db-svc
  selector:
    matchLabels:
      app: wildfly-gym-db-statefulset
  template:
    metadata:
      name: wildfly-gym-db-pod   
      labels:
        app: wildfly-gym-db-statefulset
    spec:
      containers:
      - name: postgres-container
        image: postgres:alpine
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "password"
          - name: POSTGRES_DB
            value: "gym"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgres/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: wildfly-gym-pvc 

